# init environment
# terraform version
# check if tf fmt is done
# check if tf validate is done

# terraform plan
# if commit name ends with apply do terraform apply


stages:
  - init
  - plan

init:
  stage: init
  image: hashicorp/terraform:1.8.2
  script:
    - terraform version
    - terraform fmt -check
    - echo $GOOGLE_TF_SA_KEY > /var/key.json
    - export GOOGLE_APPLICATION_CREDENTIALS=/var/key.json

plan:
  stage: plan
  image: hashicorp/terraform:1.8.2
  script:
    - terraform init
    - terraform plan

