# init environment
# terraform version
# check if tf fmt is done
# check if tf validate is done

# terraform plan
# if commit name ends with apply do terraform apply

image: registry.gitlab.com/filip3kx/terraform-images/master-1.4:de499ca5cd5e682a2bb829c8e8119a10735412fc

variables:
  GOOGLE_APPLICATION_CREDENTIALS: /var/key.json

cache:
  paths:
    - .terraform/**

before_script:
  - echo $GOOGLE_TF_SA_KEY > /var/key.json

stages:
  - test
  - plan
  - apply

check-formating:
  stage: test
  script:
    - gitlab-terraform version
    - gitlab-terraform fmt -check

validate-config:
  stage: test
  script:
    - gitlab-terraform validate

terraform-plan:
  stage: plan
  script:
    - gitlab-terraform plan -lock=false -out=plan.cache
    - gitlab-terraform plan-json
    - mv plan.json tfplan.json
  artifacts:
    paths:
      - plan.cache
    reports:
      terraform: tfplan.json

terraform-apply:
  stage: apply
  script:
    - gitlab-terraform apply
  dependencies:
    - terraform-plan
  when: manual