# init environment
# terraform version
# check if tf fmt is done
# check if tf validate is done

# terraform plan
# if commit name ends with apply do terraform apply

image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  GOOGLE_APPLICATION_CREDENTIALS: /var/key.json

cache:
  paths:
    - .terraform/**

before_script:
  - echo $GOOGLE_TF_SA_KEY > /var/key.json

stages:
  - test
  - plan
  - apply

check-formating:
  stage: test
  script:
    - gitlab-terraform fmt -check

validate-config:
  stage: test
  script:
    - gitlab-terraform validate

terraform-plan:
  stage: plan
  script:
    - gitlab-terraform init
    - gitlab-terraform plan -lock=false

terraform-apply:
  stage: apply
  script:
    - gitlab-terraform apply -auto-approve
  dependencies:
    - terraform-plan
  when: manual